version: "3"

services:
  db:
    image: mysql:latest
    container_name: mysql-dropwizardpractice
    environment:
      MYSQL_ROOT_PASSWORD: practice
    ports:
      - "3309:3306"
    command: [
      '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci',
      '--sort_buffer_size=512K', '--innodb_buffer_pool_size=1G',
      '--bulk_insert_buffer_size=256M', '--innodb_change_buffer_max_size=25',
      '--event_scheduler=on', '--sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO'
    ]